spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_registration?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root2000
  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update